name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

env:
  MONGO_URI: ${{secrets.MONGO_URI}} 
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}  
  MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
    
jobs:
    unit-testing:
        name: Unit Testing
        services:
          mongo-db:
            image: siddharth67/mongo-db:non-prod
            ports: 
              - 27017:27017
        env:
          MONGO_URI: 'mongodb://localhost:27017/superdata'
          MONGO_PASSWORD: non-prod-user
          MONGO_USERNAME: non-prod-password
        strategy:
          matrix:
            nodejs_version: [20]
            os: [ubuntu-latest]
            # exclude:
            #   - nodejs_version: 18
            #     os: macos-latest
        runs-on: ${{ matrix.os }}
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version - ${{ matrix.nodejs_version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.nodejs_version }}
          
        - name: Cache NPM Dependencies
          uses: actions/cache@v4
          with:
            path: node_modules
            key: ${{runner.os}}-node-modules-${{hashFiles('package-lock.json')}}    
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          id: nodejs-unit-testing-step
          run: npm test
          
        - name: Archive Test Result
          # always() if failure() && # (steps.nodejs-unit-testing-step.outcome == 'failure' # || steps.nodejs-unit-testing-step.outcome == 'success')
          uses: actions/upload-artifact@v3
          with:
            name: Mocha-Test-Result
            path: test-results.xml

    code-coverage:
      name: Code Coverege
      runs-on: ubuntu-latest
      # container:
      #   image: node:18
      steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup NodeJS Version 
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Cache NPM Dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{runner.os}}-node-modules-${{hashFiles('package-lock.json')}}
          
      - name: Install Dependencies
        run: npm install
     
      - name: Check Code Coverage
        continue-on-error: true 
        run: npm run coverage       
        
      - name: Archive Test Result
        uses: actions/upload-artifact@v3
        with:
          name: Code-Coverage-Result
          path: coverage      
          retention-days: 3 
    
    docker:
      name: Containerization
      needs: [unit-testing, code-coverage]
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repo
        uses: actions/checkout@v4   
      
      - name: DockeHub Login
        uses: docker/login-action@v3
        with:
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}   

      - name: Docker Build For Testing
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
          tags: ${{vars.DOCKERHUB_USERNAME}}/solar-system:${{github.sha}}    

      - name: Docker Image Testing
        run: |
          docker images
          docker run --name solar-system-app -d \
            -p 3000:3000 \
            -e MONGO_URI=$MONGO_URI \
            ${{vars.DOCKERHUB_USERNAME}}/solar-system:${{github.sha}}
          
          echo Testing image URL with wget
          wget -q -O - 127.0.0.1:3000/live | grep live
          
      - name: Docker Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{vars.DOCKERHUB_USERNAME}}/solar-system:${{github.sha}} 

    dev-deploy:
      needs: docker
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Install kubectl cli
          uses: azure/setup-kubectl@v3
          with:
            version: 'v1.26.0'

        - name: Set Kubeconfig
          uses: azure/k8s-set-context@v3
          with:
            method: kubeconfig
            kubeconfig: ${{secrets.KUBECONFIG}}

        - name: Fetch Kubernetes Cluster Details
          run: |
            kubectl version
            echo ----------
            kubectl get nodes  
            


